### PR TITLE
Work in Progress: Layout suggestion thoughts?

### PR DESCRIPTION
**Pull request by leggetter**
@Rumyra what do you think of the table layout versus the header-based layout? Table is probably easier to read, but harder to write since you need to use HTML for the lists.

The header layout has the 👍  that you can link to a [specific entry](https://github.com/leggetter/evangelistbackpacks/tree/3691b8f1d59848ca28cecf03436e25e67313f190#thule-paramount-29l-daypack).

### CODE REVIEW

**Comment by cbetta** [comment]
I prefer the tables.

**Comment by Rumyra** [comment]
I don't disagree with the layout... however:

• Do we have this much detail about each of the rucksacks? I've just been adding links people have sent me on the twits

• Does someone have the time to add in all this detail? 🤔

I can bulk out the main view if you like and hope that people add the detail - things like pros and cons can only be filled by those that own surely...

**Comment by leggetter** [comment]
I thought that if we provided reviews for bags we have or had looked into
in detail then we'd have this info.

I do 😀 but I've spends days on this!

**Comment by Rumyra** [comment]
I can give this a bit more time later - let's bulk it out...
1. @leggetter  I've added u as a collab cos you're cool
2. We'll do the table thing, but for the minute stick with the .md file whilst we collate content
3. Then we'll gh-page branch it ✨🎉💥
4. I should really make these issues

**Comment by Rumyra** [comment]
I have sorted this out

**Pull request closed without merging**
